data:
  data_dir: "data"
  data_url: "https://drive.google.com/file/d/1Xx4ozrFDDmzDCuIyUTxjzj43eARpxW1o/view?usp=sharing"
  data_filename: "test-assignment-dataset.json"
  test_data_filename: "api_test_feature_target_pairs.json"
  test_data_filename_short: "api_test_feature_target_pairs_short.json"
  data_cleaning:
    columns_to_drop: ["recommendedMassFlowRate","expectedSpeedOverGround","recommendedPower","expectedCarbonIntensityIndicator",]
    columns_nan_to_zero: ["fuelEfficiency"]
    outlier_removal: [["shaftPower", 0, 0.999]]
  data_preprocessing:
    collinear_features: ["mainEngineFuelConsumed","shaftTorque", "auxEngineVolumeFlowRate", "mainEngineVolumeFlowRate",]
    features_to_drop_task: [
      'latitude',
      'longitude',
      'draught',
      'heading',
      'courseOverGround',
      'status',
      'mainEngineVolumeFlowRate',
      'mainEngineDensity',
      'mainEngineTemperature',
      'mainEngineFuelConsumed',
      'auxEngineMassFlowRate',
      'auxEngineVolumeFlowRate',
      'auxEngineDensity',
      'auxEngineTemperature',
      'shaftSpeed',
      'shaftTorque',
      'specificFuelOilConsumption',
      'timestamp',
      'fuelEfficiency',
      'gust',
      'swellPeriod',
      'wavePeriod',
      'windWaveDirection',
      'windWaveHeight',
      'windWavePeriod',
      'salinity',
      'seaLevel']
    task_features: [
      "windSpeed",
      "windDirection",
      "waveHeight",
      "waveDirection",
      "swellHeight",
      "swellDirection",
      "currentSpeed",
      "currentDirection",
      "airTemperature",
      "mainEngineMassFlowRate"]
    preprocessor_file: "tuning_prep.pkl"
  target_columns: ["shaftPower", "speedOverGround"]
feature_engineering:
  base_angle_feature: "heading"
  angular_features: ["windDirection","currentDirection","waveDirection","swellDirection","windWaveDirection"]
  environment_forces_features: [["windDirection","windSpeed"],["currentDirection", "currentSpeed"]]
  base_time_feature: "timestamp"
hyperparameter_tuning:
  random_search_ranges:
    'base_estimator__learning_rate': [0.01, 0.3]  # uniform distribution within the interval, default=0.1 
    'base_estimator__n_estimators': [50, 140] # random int within the interval, default=100 (RAM intensive)
    'base_estimator__max_depth': [2, 13] # default=6 (RAM intensive)
    'base_estimator__min_child_weight': [0.5, 30] # for regularization, default=1
  random_search_file: "random_search_xgb.pkl"
  grid_search_file: "grid_search_xgb.pkl"
models:
  model_dir: "models"
  model_dir_all_feats: "models/full_feature_set"
  final_model_file: "final_model.pkl"
  best_tuned_params: 
    'learning_rate': 0.2683329083149937
    'max_depth': 12
    'min_child_weight': 14.5268163746471
    'n_estimators': 125
  model_names:
    full_feat: "full_feature_set"
    limited_feat: "task_specific_limited"
api:
  host: "127.0.0.1"
  port: 8000
  predict_endpoint: "/predict"
